//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18408
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RibbonNotepad.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RibbonNotepad.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   編集 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusTextEditMenu {
            get {
                return ResourceManager.GetString("StatusTextEditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   コピー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusTextEditMenuItemCopy {
            get {
                return ResourceManager.GetString("StatusTextEditMenuItemCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   切り取り に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusTextEditMenuItemCut {
            get {
                return ResourceManager.GetString("StatusTextEditMenuItemCut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日付と時刻 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusTextEditMenuItemDayAndData {
            get {
                return ResourceManager.GetString("StatusTextEditMenuItemDayAndData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   削除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusTextEditMenuItemDel {
            get {
                return ResourceManager.GetString("StatusTextEditMenuItemDel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusTextEditMenuItemFind {
            get {
                return ResourceManager.GetString("StatusTextEditMenuItemFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   次を検索 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusTextEditMenuItemFindNext {
            get {
                return ResourceManager.GetString("StatusTextEditMenuItemFindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行へ移動 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusTextEditMenuItemMoveToLine {
            get {
                return ResourceManager.GetString("StatusTextEditMenuItemMoveToLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   貼り付け に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusTextEditMenuItemPaste {
            get {
                return ResourceManager.GetString("StatusTextEditMenuItemPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   置換 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusTextEditMenuItemReplace {
            get {
                return ResourceManager.GetString("StatusTextEditMenuItemReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   全て選択 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusTextEditMenuItemSelectAll {
            get {
                return ResourceManager.GetString("StatusTextEditMenuItemSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   元に戻す に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusTextEditMenuItemUndo {
            get {
                return ResourceManager.GetString("StatusTextEditMenuItemUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイル に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusTextFileMenu {
            get {
                return ResourceManager.GetString("StatusTextFileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規作成 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusTextFileMenuItemNew {
            get {
                return ResourceManager.GetString("StatusTextFileMenuItemNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルを開く に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusTextFileMenuItemOpen {
            get {
                return ResourceManager.GetString("StatusTextFileMenuItemOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷設定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusTextFileMenuItemPageSetting {
            get {
                return ResourceManager.GetString("StatusTextFileMenuItemPageSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   印刷 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusTextFileMenuItemPrint {
            get {
                return ResourceManager.GetString("StatusTextFileMenuItemPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   上書き保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusTextFileMenuItemSave {
            get {
                return ResourceManager.GetString("StatusTextFileMenuItemSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前をつけて保存 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StatusTextFileMenuItemSaveAs {
            get {
                return ResourceManager.GetString("StatusTextFileMenuItemSaveAs", resourceCulture);
            }
        }
    }
}
